In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import mean_squared_error

import lightgbm as lgb

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [ ]:
train_df = pd.read_csv("/content/drive/MyDrive/python-for-biginner/House Prices/train.csv")
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
train_df.shape

(1460, 81)

In [ ]:
train_df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object
HeatingQC         object
CentralAir        object
Electrical        object
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC            object
Fence             object
MiscFeature       object
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
dtype: object

In [ ]:
pd.set_option('display.max_rows', 100)

In [ ]:
train_df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [ ]:
train_df["OverallQual"].head()

0    7
1    6
2    7
3    7
4    8
Name: OverallQual, dtype: int64

In [ ]:
train_df["MSSubClass"].head()

0    60
1    20
2    60
3    70
4    60
Name: MSSubClass, dtype: int64

In [ ]:
#特徴量
features = ["OverallQual", "MSSubClass"]

X_train = train_df[features] #全体品質,居住面積
y_train = np.log1p(train_df["SalePrice"]) #対数変換しない？

In [ ]:
print(X_train.shape)
print(y_train.shape)

(1460, 2)
(1460,)

In [ ]:
params = {
    "boosting_type" : "gbdt",
    "objective" : "regression",
    "metric" : "rmse",
    "learning_rate" : 0.1,
    "num_leaves" : 16,
    "n_estimators" : 100000,
    "random_state" : 123,
    "importance_type" : "gain",
}

In [ ]:
#cv
n_splits = 5
cv = KFold(n_splits=n_splits, shuffle=True, random_state=123)

metrics = []
imp = pd.DataFrame()

for nfold, (train_idx, val_idx) in enumerate(cv.split(X_train)):
  x_tr, y_tr = X_train.iloc[train_idx], y_train.iloc[train_idx]
  x_va, y_va = X_train.iloc[val_idx], y_train.iloc[val_idx]

  print("学習用:", x_tr.shape, y_tr.shape)
  print("評価用:", x_va.shape, y_va.shape)

  model = lgb.LGBMRegressor(**params)
  model.fit(
    x_tr,
    y_tr,
    eval_set=[(x_tr, y_tr), (x_va,y_va)],
    callbacks=[
        lgb.early_stopping(stopping_rounds=100, verbose=True),
        lgb.log_evaluation(0),
    ])

  y_tr_pred = model.predict(x_tr)
  y_va_pred = model.predict(x_va)

  rmse_tr = np.sqrt(mean_squared_error(y_tr, y_tr_pred))
  rmse_va = np.sqrt(mean_squared_error(y_va, y_va_pred))

  print("[RMSE] tr: {:.2f}, va: {:.2f}".format(rmse_tr, rmse_va))

  metrics.append([nfold, rmse_tr, rmse_va])

  _imp = pd.DataFrame({
        "col": X_train.columns,
        "imp": model.feature_importances_,
        'nfold': nfold
        })

  imp = pd.concat([imp, _imp], axis=0, ignore_index=True)

学習用: (1168, 2) (1168,)
評価用: (292, 2) (292,)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000455 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 2
[LightGBM] [Info] Start training from score 12.021806
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[82]	training's rmse: 0.205543	valid_1's rmse: 0.202439
[RMSE] tr: 0.21, va: 0.20
学習用: (1168, 2) (1168,)
評価用: (292, 2) (292,)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000048 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 2
[LightGBM] [Info] Start training from score 12.014343
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[34]	training's rmse: 0.204619	valid_1's rmse: 0.216304
[RMSE] tr: 0.20, va: 0.22
学習用: (1168, 2) (1168,)
評価用: (292, 2) (292,)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000054 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 2
[LightGBM] [Info] Start training from score 12.029358
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[126]	training's rmse: 0.205845	valid_1's rmse: 0.214324
[RMSE] tr: 0.21, va: 0.21
学習用: (1168, 2) (1168,)
評価用: (292, 2) (292,)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000055 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 2
[LightGBM] [Info] Start training from score 12.029417
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[59]	training's rmse: 0.201028	valid_1's rmse: 0.223079
[RMSE] tr: 0.20, va: 0.22
学習用: (1168, 2) (1168,)
評価用: (292, 2) (292,)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000047 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26
[LightGBM] [Info] Number of data points in the train set: 1168, number of used features: 2
[LightGBM] [Info] Start training from score 12.025363
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[33]	training's rmse: 0.210955	valid_1's rmse: 0.201608
[RMSE] tr: 0.21, va: 0.20

In [ ]:
metrics = np.array(metrics)
print(metrics)

print("[cv ] tr: {:.2f}+-{:.2f}, va: {:.2f}+-{:.2f}".format(
    metrics[:,1].mean(), metrics[:,1].std(),
    metrics[:,2].mean(), metrics[:,2].std(),
))
#CV結果を表にして、平均＋ーばらつきで見る

[[0.         0.20554275 0.20243881]
 [1.         0.20461929 0.21630446]
 [2.         0.2058447  0.21432422]
 [3.         0.20102835 0.22307941]
 [4.         0.21095523 0.20160804]]
[cv ] tr: 0.21+-0.00, va: 0.21+-0.01

In [ ]:
imp = imp.groupby("col")["imp"].agg(["mean", "std"])
imp.columns = ["imp", "imp_std"]

imp_df = imp.sort_values(by='imp', ascending=False)
imp_df.head(30)
#特徴量重要度をnfold平均で安定化して見る

                    imp    imp_std
col
OverallQual  649.948566  14.607817
MSSubClass    70.142910   5.246156

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/python-for-biginner/House Prices/test.csv')
test.shape

(1459, 80)

In [ ]:
X_test = test[features]
X_test.shape

(1459, 2)

In [ ]:
y_test_pred = model.predict(X_test)
y_test_pred = np.expm1(y_test_pred)

df_submit = pd.DataFrame({
    'Id': test.Id,
    'SalePrice': y_test_pred
})
df_submit

        Id      SalePrice
0     1461  134841.104013
1     1462  166453.434672
2     1463  147577.002743
3     1464  182261.677921
4     1465  226514.557723
...    ...            ...
1454  2915   96862.705023
1455  2916   96862.705023
1456  2917  134841.104013
1457  2918  141782.679403
1458  2919  217673.312791

[1459 rows x 2 columns]

In [ ]:
df_submit.to_csv("hp-submission_baseline2.csv", index=False)

In [ ]:
from google.colab import files
files.download("hp-submission_baseline2.csv")